NumPy(short for Numerical Python): Python library used for efficient numerical calculations.It provides tools to work with large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them.

Key features of NumPy:

*N-dimensional Arrays: ndarray -> multidimensional arrays of homogeneous data types

*ndarray -> speed and memory [built on C] as compared to List

*Mathematical Operations:mean, sum, max, min, standard deviation, etc.

*Allows vectorized operations ->> absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code (which makes the code more concise and easier to read and also fewer lines means there will be fewer bugs in the code)

After installing NumPy, it may be imported into Python code like:

In [ ]:
import numpy as np

Most NumPy arrays have some restrictions. For instance:

*All elements of the array must be of the same type of data.
*Once created, the total size of the array can’t change.
*The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns

Array attributes: 
This section covers the ndim, shape, size, and dtype attributes of an array.
The number of dimensions of an array is contained in the ndim attribute.


In [15]:
import numpy as np

In [17]:
n= np.array([15,20,36,41,24,33])
print(n)


[15 20 36 41 24 33]


In [23]:
print(type(n))

<class 'numpy.ndarray'>


In [27]:
n.dtype  #data type is recorded in the dtype attribute.(Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”.)

dtype('int64')

In [29]:
n.ndim      #number of dimensions of an array

1

In [31]:
n.shape    #shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

(6,)

In [33]:
n.size   #total number of elements in array is contained in the size attribute.

6

How to create basic arrays:
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [35]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.ones(2)

array([1., 1.])

In [39]:
np.empty(3)

array([0., 0., 0.])

In [41]:
np.arange(7) #an array with a range of elements

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
np.arange(1,20,4)   #anarray that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.


array([ 1,  5,  9, 13, 17])

In [45]:
np.linspace(0,15,num=3) #o create an array with values that are spaced linearly in a specified interval

array([ 0. ,  7.5, 15. ])

Adding, removing, and sorting elements: This section covers np.sort(), np.concatenate()


In [47]:
np.sort(n)      #sorting the numbers in ascending order with

array([15, 20, 24, 33, 36, 41])

In [49]:
num1 = np.array([1, 2, 3, 4])  #concatenate the arrays
num2 = np.array([5, 6, 7, 8])
np.concatenate((num1,num2))

array([1, 2, 3, 4, 5, 6, 7, 8])